#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          lightm
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of lightm
# Description:       starts instance of lightm
### END INIT INFO

# Script name
NAME=lightm
FILE=lightm.pl
DIR=/usr/local/bin/web/
RUN_AS=pi
PID_FILE=/var/run/lightm/lightm.pid
DESC=lightm
DAEMON=/usr/bin/python
PID_PATH=`dirname $PID_FILE`

test -x $DAEMON || exit 0

set -e

if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
    chown $RUN_AS $PID_PATH
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

case "$1" in
    start)
        echo "Starting $DESC"
        start-stop-daemon --background -d $DIR -c $RUN_AS --start --pidfile $PID_FILE --exec $DAEMON -- $DIR$FILE
        ;;
    stop)
        echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        ;;

    restart|force-reload)
        echo "Restarting $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        start-stop-daemon --background -d $DIR -c $RUN_AS --start --pidfile $PID_FILE --exec $DAEMON -- $DIR$FILE
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
